### PR TITLE
Allow sign in using custom authentication flow for Cognito User Pools

### PR DESCRIPTION
**Pull request by buggy**
*Issue #, if available:*

#525 

*Description of changes:*

Cognito User Pools support custom authentication flows which allows passwordless logins. To support this with Amplify I have modified `Auth.signIn()` to make the password optional. If it is not provided then `initiateAuth()` is used instead of `authenticateUser()`. This allows the developer to completely customize the authentication flow and potentially remove the requirement for a password. Custom challenges can be responded to by calling `Auth.sendCustomChallengeAnswer()`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by buggy** [comment]
1. Modifying `signIn()` to make the password optional is my preferred approach as it feels natural but I'm open to the idea of making password required again and adding a new method to trigger custom authentication flows.

2. I've extract the callbacks from the original `signIn()` into a method called `authCallbacks()` so password and passwordless logins use the same callbacks. When reading the Cognito User Pools docs, especially around custom authentication flows, it occurred to me that there isn't a set path through the authentication process but it looks like the Auth module and (possibly) amazon-cognito-identity-js seem to make assumptions by restricting the number of callbacks in the following functions

- `verifySoftwareToken` in `verifyTotpToken`
- `sendMFACode` in `confirmSignIn`
- `completeNewPasswordChallenge` in `completeNewPassword`

For example: After completing the MFA verification I might need to complete a custom challenge but `sendMFACode()` seems to assume my only options are a successful login or failure. Have I missed something?

**Comment by buggy** [comment]
@yuntuowang This PR is now ready for review. The public interface changes minimal.

1. For amazon-cognito-identity-js it adds a type definition for `initiateAuth()`

2. For aws-amplify it makes the password optional for `Auth.signIn()`. If it is not provided then it uses `initiateAuth()` to allow passwordless logins.

3. For aws-amplify it also adds `Auth.sendCustomChallengeAnswer()` so you can response to a custom challenge.

When I manually tested this against a Cognito User Pool with custom triggers it correctly returned `CUSTOM_CHALLENGE` with the `publicChallengeParameters` from the Lambda going into the `challengeParam` on the client. If I respond with the incorrect answer it fails and if I get it correct the credentials are issued.

**Comment by buggy** [comment]
@powerful23 I was trying to merge master so I could fix the conflicts but I'm struggling to understand your changes to `auth-unit-test.ts` and `auth-unit-test-rn.ts` in https://github.com/aws/aws-amplify/commit/957d7eab3d7fe84c7e57f72fa4b5484798928547

After your changes to `authOptions` and `authOptionsWithNoUserPoolId` no longer implement the `AuthOptions` interface but they're being passed into the constructor for `Auth` (see the many  `const auth = new Auth(authOptions);`) which expects an object implementing the `AuthOptions` interface. I suspect this is a mistake.

**Comment by powerful23** [comment]
@buggy good point! fixed in #695

**Comment by sonipriya10** [comment]
Can you provide the working example of passwordless authentication?

**Comment by buggy** [comment]
@Loghrenar

> Do we have some visibility on this issue ?

I've updated the PR so it's based on the current master and builds correctly.

> When will this be merged ?

@mlabieniec has tagged it for 0.5 but I'm really hoping it can make it into 0.4. The original PR is over a month old. All I can do is keep the PR up to date so that it can be merged when they're ready.

> Will the doc be updated with passwordless examples ?

The PR includes updated docs for Amplify. If you call `Auth.signIn()` without a password it triggers the custom authentication flow which allows passwordless authentication.

**Comment by buggy** [comment]
@mlabieniec Any chance we can get this reviewed and into 0.4? It would also be good to get this merged before amazon-cognito-identity-js@2.1 as it updates packages/amazon-cognito-identity-js/index.d.ts.

**Comment by Loghrenar** [comment]
Hey @buggy,

Back from holidays, i see this pr is not merged yet. When do you think this one will be merged ? (I'd like to change my custom auth with cognito to a new beautiful one with amplify ^^)

Assuming this one will not be merged, is there an alternative to custom authentication with amplify (not using congito-identity-js custom auth) ?

Thanks in advance.

**Comment by buggy** [comment]
@Loghrenar I can't give you a definitive answer because I don't work for AWS. It looks like there was an attempt to get this into 0.4 but that didn't happen. It's currently tagged for 0.5 but all I can really do is keep the PR up to date.

**Comment by Loghrenar** [comment]
@buggy, thank you, i just realized that you can just keep this pr up to date ^^'
Did you have any feedback on why it failed to be merged in 0.4 ?

**Comment by mlabieniec** [comment]
Thanks for the patience we are in the middle of testing this trying to get it merged asap.

**Comment by Loghrenar** [comment]
Hey @mlabieniec, 

Do you have any news about this pr ?

**Comment by buggy** [comment]
@powerful23 It took a bit of experimenting to fully understand custom authentication flows. You'll find my create/define/verify auth challenge handlers I'm using in https://github.com/buggy/project-x-server/tree/master/shopify/src

Define auth challenge will have an empty session the first time it's called.

**Comment by powerful23** [comment]
@buggy gotcha. Thanks for your prompt response! I was following the sample code from Cognito docs which will throw error when the session is empty. I think we may need to add those working lambda sample in the amplify doc so that people won't get confused about that.

**Comment by buggy** [comment]
If you're still having trouble then let me know and I'll spin up a working user pool for you along with the code to do it yourself :)

I know how much time I spent debugging Lambda when I first tried.

**Comment by powerful23** [comment]
Thanks! It's working now! I think we should add those lambda sample functions in the doc. Would you like to do that or I can do it. :)

**Comment by buggy** [comment]
I can add them. I need to make one change anyway to the Lambda anyway.

**Comment by Loghrenar** [comment]
Hey @powerful23,

Did you check this pr ? Do we have any news about a potential merge ? 
This one is really really long to validate...

Thanks.

**Comment by powerful23** [comment]
@Loghrenar we are about to merge that as long as @buggy update the lambda sample functions.

**Comment by Loghrenar** [comment]
Nice 👍 
Waiting for @buggy so. Thank you

**Comment by buggy** [comment]
I'll get it updated in the next 24 hours :)

**Comment by powerful23** [comment]
@buggy thanks! Let me know when the update is finished and we can ship it.

**Comment by Loghrenar** [comment]
Hey @buggy,
Coming for the news, did you have the time to update the last changes ?

**Comment by buggy** [comment]
@powerful23 It's updated and ready to merge once the checks pass

**Comment by andidev** [comment]
@buggy
Great work! Do you by any chance have a complete example of how to implement a passwordless logon with lambdas and custom authentication flow? I'm talking about the lambda implementation.

**Comment by buggy** [comment]
@andidev Actually, I do. The Amplify docs have a modified version of my Lambda's from https://github.com/buggy/project-x-server/tree/master/shopify. You'll mostly be interested in `createAuthChallenge.ts`, `defineAuthChallenge.ts` and `verifyAuthChallengeResponse.ts`.

I'm hoping that I'll find time to write a detailed article about this in the next week or two explaining how you can use passwordless login to add support for any OAuth provider to Ampify/Coginto User Pools.

**Comment by VicFrolov** [comment]
Way to go buggy!  So what are the next steps at this point? I see it was moved from backlog to done and @beta. Exciting news! Is there any ETA on this being in the latest version?

**Comment by skonb** [comment]
I tested this but still got error of 'Invalid Username or Password'. initiateAuth always returns on onFailure. 

```
       Auth.signIn(this.generateUsernameWithEmail(email)).then(user => {
            this.user = user;
            onSuccess();
        }, error => {
            if (error.code === 'UserNotConfirmedException') {
                this.resendConfirmationCodeByEmail(email, (thisError) => {
                    if (thisError !== null && thisError !== undefined) {
                        onFailure(thisError);
                    } else {
                        onSuccess();
                    }
                });
            } else {
                onFailure(error);
            }
        });
```

**Comment by kevinsperrine** [comment]
@buggy Did you ever get around to writing up the OAuth details? I'd love to do the same thing with Spotify.

**Comment by icj217** [comment]
I'm having trouble getting this to work. I've confirmed that my Define Auth Challenge lambda is returning the proper response. In inspecting the network request I see that Cognito is returning a response like so:
```json
{
    "ChallengeName": "SMS_MFA",
    "ChallengeParameters": {
        "USERNAME": "my.username@example.com"
    },
    "Session": "..."
}
```
But when logging out the result of signIn I'm not seeing any challenge being presented:
```json
{
    "Session": null,
    "authenticationFlowType": "CUSTOM_AUTH",
    "client": {
        "endpoint": "https://cognito-idp.us-east-1.amazonaws.com/",
        "userAgent": "aws-amplify/0.1.x js"
    },
    "pool": {
        "advancedSecurityDataCollectionFlag": true,
        "client": {
            "endpoint": "https://cognito-idp.us-east-1.amazonaws.com/",
            "userAgent": "aws-amplify/0.1.x js"
        },
        "clientId": "CLIENT_ID",
        "storage": {
            ...
        },
        "userPoolId": "USER_POOL_ID"
    },
    "signInUserSession": {
        "accessToken": {
            "jwtToken": "",
            "payload": {}
        },
        "clockDrift": null,
        "idToken": {
            "jwtToken": "",
            "payload": {}
        },
        "refreshToken": {
            "token": ""
        }
    },
    "storage": {
        ...
    },
    "username": "my.username@example.com"
}
```
I've made sure that my aws-amplify is up to date (1.1.6). I'm assuming that SMS_MFA is a valid challenge to be returned in a CUSTOM_AUTH flow, since its alluded to in multiple parts of the Cognito documentation.

**Comment by powerful23** [comment]
@icj217 if you are using custom challenge flow, the `ChallengeName` should always be the `CUSTOM_CHALLENGE`: https://aws-amplify.github.io/amplify-js/media/authentication_guide#using-a-custom-challenge

**Comment by icj217** [comment]
@powerful23 thanks for the tip. I ended up realizing this and decided to manually implement MFA within the CUSTOM_CHALLENGE using SNS.

**Comment by hoang-innomizetech** [comment]
For now, we have used migration trigger to authenticate user in AD or database.

**Comment by thedesidevil** [comment]
@buggy @powerful23 I am assuming a password is still required during user sign-up though correct?

**Pull request merged**
