### PR TITLE
Need to stringify objects when storing them in Cache

### LINKED ISSUE #424: Cache.setItem expects a string value, not an object
Do you want to request a feature or report a bug? Bug

What is the current behavior?
When calling `Cache.setItem`, I believe the `value` argument (the second argument) must be a string. This is just a guess because when calling `Cache.getItem`, JSON.parse fails with an `object` error. Specifically, I believe this line needs to wrap the second argument with `JSON.stringify`: https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L721. I've tested this locally on an app that implements Facebook login and it resolves this issue.

I can submit a PR with a fix, but am having trouble running `npm run build` in the `aws-amplify` package. Any correct build instructions would be appreciated. 

What is the expected behavior?
To not get an error when pulling an object via `Cache.getItem`.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions? Latest aws-amplify (0.2.9) and aws-amplify-react-native (0.2.5).

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

### PR DESCRIPTION
**Pull request by rlmartin**
Resolves #424

*Issue #, if available:*

*Description of changes:*
FYI I wasn't sure which files from `yarn build` to include, so I only included what seemed like related files. I mainly wasn't sure about all the `packages/aws-amplify/dist/aws-amplify*.js*` files.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rlmartin** [comment]
Actually, let me add a unit test of the Cache model to this PR.

**Comment by powerful23** [comment]
@rlmartin The cache module will stringify objects automatically so you really don't need to do it when calling it.

**Comment by rlmartin** [comment]
@powerful23 I wasn't seeing that behavior - was getting `JSON.parse` errors on getItem that led me to believe that the object is going in as `obj.toString()` instead of `JSON.stringify(obj)`. But, as I mentioned above, let me write a unit test to prove this.

**Comment by powerful23** [comment]
@rlmartin are you using Cache in react-native? That was a bug in AsyncStorageCache which you will have when using it in react-native. We just fixed that this week #412

**Comment by rlmartin** [comment]
@powerful23 Yes, that fixes my problem. Please cut a new version of aws-amplify-react-native so I can pick up that fix :) Thanks.

**Comment by powerful23** [comment]
@rlmartin We just published a beta version ```v0.2.6@beta``` so you can try that one for now.

**Pull request closed without merging**
