### PR TITLE
Signup custom attr

### PR DESCRIPTION
**Pull request by powerful23**

### CODE REVIEW

**Comment by xpolb01** [comment]
Hi guys! When will this PR be merged? We really need it to move forward with SignUp 🤓

**Comment by powerful23** [comment]
for issue #18

**Comment by MatteCarra** [comment]
What about validation data? Why isn't it included?
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html#API_SignUp_RequestSyntax

**Comment by mtstrong17** [comment]
When will this be on NPM?

**Comment by mlabieniec** [comment]
@mtstrong17 publishing to npm momentarily

**Pull request merged**
