### PR TITLE
Make `withAuthenticator` HOC configurable

### PR DESCRIPTION
**Pull request by rlmartin**
This will allow for building custom SignIn, Loading, etc components but still leveraging the ease of `withAuthenticator`.

### CODE REVIEW

**Comment by mlabieniec** [comment]
@rlmartin the structure has changed a bit here, the core logic has moved into aws-amplify, can you have a look and see if you can merge these into the latest. Thanks.

**Comment by rlmartin** [comment]
@mlabieniec sure I'll take a look.

**Comment by rlmartin** [comment]
@mlabieniec in case you missed it, I updated this PR.

**Comment by powerful23** [comment]
@rlmartin could you provide us an example to show how does it work with the code? I am trying to pass a customized component into the array and expecting to just get that component rendered like:
```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';

export default class myComponent extends React.Component {
    render() {
        return (
            <Button title="Record" />
        );
    }
}
``` 
and using it in the hoc like:
```
withAuthenticator(App, false, [myComponent]);
```
But turns out to be an error saying:
```Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.```

Thanks.

**Comment by rlmartin** [comment]
Hi @powerful23 - I believe that's an error from React Native. You need to pass in an instance of the class, not the class itself (i.e. `<myComponent />`). This is how the `Authenticator` class works: https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify-react-native/src/Auth/Authenticator.js#L107

I'll update the README :)

**Pull request merged**
