### PR TITLE
Update crypto-browserify to latest

### PR DESCRIPTION
**Pull request by digigarlab**
*Description of changes:*

Update `crypto-browserify` to `3.12.0`.

The current version suffers of a severe vulnerability:

```
✗ High severity vulnerability found on crypto-browserify@1.0.9
- desc: Insecure Randomness
- info: https://snyk.io/vuln/npm:crypto-browserify:20140722
```

No regression should occur, even though I updated to 2 major version forward. Currently 3 functions of the lib are used:
- `crypto.createHash` is directly pulled from `create-hash`
- `crypto.createHmac` is directly pulled from `create-hmac`
- `crypto.randomBytes` is what we want to fix

Since there is no proper test suite in this project (`npm test` run `eslint`!), I had to resort to manual testing and it seems to work fine.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by richardzcode** [comment]
```
npm remove --save crypto-browserify
npm install --save crypto-browserify@3.12.0
npm run build
```

Got a bunch of these errors:
```
ERROR in ./~/browserify-sign/browser/algorithms.json
Module parse failed: /Users/.../aws-amplify/packages/amazon-cognito-identity-js/node_modules/browserify-sign/browser/algorithms.json Unexpected token (2:27)
You may need an appropriate loader to handle this file type.
```

**Comment by digigarlab** [comment]
@richardzcode I didn't get those errors in my branch but I can reproduce in the latest master.

Those are webpack errors that occur when running `npm run build:umd`.

A npm ls show that:

```├─┬ crypto-browserify@3.12.0
│ ├─┬ browserify-cipher@1.0.0
│ │ └── browserify-aes@1.1.1
│ └─┬ browserify-sign@4.0.4
│   └─┬ parse-asn1@5.1.0
│     └── browserify-aes@1.1.1  deduped
└─┬ webpack@1.15.0
  └─┬ node-libs-browser@0.7.0
    └─┬ crypto-browserify@3.3.0
      └── browserify-aes@0.4.0
```

`weback@1.15.0` depends on `browserify-aes@0.4.0`, but `crypto-browserify@3.12.0` brings `browserify-aes@1.1.1`.
Now it seems that webpack is trying to read all files in `./node_modules/browserify-aes/modes/` (which is `@1.1.1`) instead of `./node_modules/webpack/node_modules/browserify-aes/modes/`.

A workaround would be to add the `json-loader` to the webpack config, but the best solution is probably to upgrade webpack too.

**Comment by sunoru** [comment]
The update for crypto-browserify is really needed, or this may occur when using Webpack and UglifyJS along with aws-amplify: https://github.com/aws/amazon-cognito-identity-js/issues/679

**Comment by powerful23** [comment]
Closing this pr as the change has been merged.

**Pull request closed without merging**
