### PR TITLE
Add query strings

### LINKED ISSUE #127: Cannot get API.get to work
Hello,

I'm trying to use API.get and pass queryStringParameters in the request so these params can be accessed from Lambda function's 'event' but this doesn't seem to work.

```
    const val1 = 'test123';
    const val2 = 'test123';

    let myInit = {
        'queryStringParameters': {
            'key1': val1,
            'key2': val2
        },
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        }
    };

    return API.get(apiName, path, myInit).then(data => {
        return data;
    }).catch(err => console.log('error.', err));

```

Notes:
1. I've added the query params in Api Gateway method (URL Query String Parameters)
2. In Lambda function's logs i can see `queryStringParameters: null,`
3. API Gateway Integration request details (Use Lambda Proxy integration is enabled)
image
4. I've tried adding the query params as part of path as abc?key1=val1&key2=val2 etc. but didn't work as well
5. API.post works good (when passing the params in body

Let me know if you need more details

Thanks in advance.

### PR DESCRIPTION
**Pull request by nuttmeister**
*Issue #, if available:*
Fixes #127

*Description of changes:*
- Added support for axios clients params option (query strings) in RestClient.ts.
- Query strings can be set in path or by setting "queryStringParameters" in init obj. They can be used in tandem and will all be added to the axios params option.
- Correctly encode query strings in Signer.ts. We must encode ' signs for example. Previously this made the signer produce an wrong signature.
- The query strings will automatically be URI encoded both by the Signer and the axios client.

PS. Not a JavaScript/TypeScript programmer. So be kind :)
Might not have made all the correct javascript-esque coding choices.

### CODE REVIEW

**Comment by mlabieniec** [comment]
@nuttmeister i fixed the conflict, can you update the coverage on the RestClient so we can get this merged? Thanks.

**Comment by nuttmeister** [comment]
@mlabieniec sorry, been away. I will try and fix the coverage this weekend so that it can be merged.

**Comment by elorzafe** [comment]
Hi @nuttmeister thank you very much for your PR :-) 

Now the library is supporting query strings so I will close this PR. Sorry for the late response.

Thanks!

**Comment by elorzafe** [comment]
Sorry @nutmeister, now is working the query string on the url. I will check how to fix the issue when queryStrings are used on init object.

**Pull request closed without merging**
