### PR TITLE
Sign in with USER_PASSWORD_AUTH flow

### PR DESCRIPTION
**Pull request by pjarts**
Feature request.

We want to migrate users using the "Migrate Users" trigger in our Cognito user pool, but in order for the triggered lambda to be able to verify the user password against our current user directory we need AWS Amplify to sign in the user with the `USER_PASSWORD_AUTH` flow, according to the documentation [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-import-using-lambda.html) (step 2).

Do you think `authenticationType` could be added to `AuthOptions`? Then, `Auth.signInWithPassword` could use that value when creating `AuthenticationDetails`.

### CODE REVIEW

**Comment by pjarts** [comment]
Simple change. Let me know if you need unit tests etc.

**Comment by pjarts** [comment]
There's a quite good documentation [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-import-using-lambda.html) on how to use the migration trigger. Basically, you configure the trigger to invoke a Lambda function that validates the user credentials it receives against your own user directory. If the credentials are valid you return a set of user attributes that will be used by Cognito to create a new user in the user pool. If they are invalid you invoke the callback with an error that will propagate back to your app and Cognito will not create a user. If a user already exists for the provided username (or email/phone number, depending on your alias configuration) Cognito will authenticate against that user and not invoke your Lambda at all. There's more documentation on how to write your Lambda [here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-migrate-user.html).

There reason for this pull request is that both the Cognito User Pool and AWS Amplify is configured to use the `USER_SRP_AUTH` flow by default ([here's](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol) a link to Wikipedia), meaning the password is somehow encrypted on the client side before it's sent to Cognito. This is a more secure way of passing user credentials to the back-end, but the problem is that the Lambda invoked by the migration trigger won't be able to verify the password, making a seamless migration from your current user directory to Cognito impossible. In order to authenticate users in a more traditional manner, with username and password being sent unencrypted to the back-end, you need two things:

1. You have to enable `USER_PASSWORD_AUTH` flow for your user pool. In the AWS console, this is done by ticking the checkbox at _App Clients > Show Details > Enable username-password (non-SRP) flow..._

2. You need to set the `authenticationFlowType` property on your `CognitoUser` instance (from the _amazon-cognito-identity-js_ package) to `USER_PASSWORD_AUTH` (see snippet below). Since AWS Amplify is a wrapper around that package, this pull request is needed to enable the app to set that property.

Below is a snippet from _./src/Cognito.js_ in the _amazon-cognito-identity-js_ package describing the initialisation, setter and usage of the `authenticationFlowType` property on a CognitoUser instance.
```js
constructor(data) {
  ...
  this.authenticationFlowType = 'USER_SRP_AUTH';
  ...
}
...
setAuthenticationFlowType(authenticationFlowType) {
  this.authenticationFlowType = authenticationFlowType;
}
...
authenticateUser(authDetails, callback) {
  if (this.authenticationFlowType === 'USER_PASSWORD_AUTH') {
    return this.authenticateUserPlainUsernamePassword(authDetails, callback);
  } else if (this.authenticationFlowType === 'USER_SRP_AUTH') {
    return this.authenticateUserDefaultAuth(authDetails, callback);
  }
  return callback.onFailure(new Error('Authentication flow type is invalid.'));
}
```

[More documentation on Cognito auth flows](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html#amazon-cognito-user-pools-custom-authentication-flow)

This pull request will check the `_config` property on the `Auth` class when `this.createCognitoUser` is called and set the `authenticationFlowType` parameter on the user object if present in the `_config`. This approach will set the `authenticationFlowType` (if set in config) on all user instances created by the Auth class. Maybe a better solution is to only set it in the `signInWithPassword` method, just like you do in the `signInWithoutPassword` method (see snippet below)? 

```js
private signInWithoutPassword(username: string): Promise<any> {
  const user = this.createCognitoUser(username);
  user.setAuthenticationFlowType('CUSTOM_AUTH'); // <-- flow type is set here
  const authDetails = new AuthenticationDetails({
    Username: username,
  });
  return new Promise((resolve, reject) => {
    user.initiateAuth(authDetails, this.authCallbacks(user, resolve, reject));
  });
}
```

**Comment by powerful23** [comment]
@pjarts Great! Thanks for your explanation. But what I mean is that could you write a section around how to setup the whole Auth flow in the [authentication guide](https://aws.github.io/aws-amplify/media/authentication_guide) for example:
```
Sign in with USER_PASSWORD_AUTH
1. setup lambda function, you can follow the link here and here
...
4. Auth.configure({
     authenticationTypeFlow: ...
})
```
So that we can merge it along with your code and @mbahar can review the doc.
Let me know if you are willing to write that or I can do it after merging this one. Thanks!

**Comment by pjarts** [comment]
Right, sorry for the confusion. I'll update the PR with added docs. English is not my primary language though, but I'll try my best.

**Comment by powerful23** [comment]
@pjarts Thanks a lot!

**Pull request merged**
