### PR TITLE
Allow CUSTOM_AUTH in authenticateUser

### PR DESCRIPTION
**Pull request by abemusic**
*Issue #, if available:*

#525 

*Description of changes:*

Allow CUSTOM_AUTH flow type in the authenticateUser method.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by buggy** [comment]
@abemusic You don't need to modify amazon-cognito-identity-js to use custom auth flow. As @yuntuowang said there's already `initiateAuth()` that you should be using to start that flow. See #566 if you're not sure how to use it. I should have time to finish writing tests for that PR later today which will add support for  custom auth flows to the Auth class inside Amplify.

**Comment by yuntuowang** [comment]
@buggy, awesome reply and PR work!

**Comment by abemusic** [comment]
@buggy @yuntuowang thanks for the feedback! 

Can I get a bit more clarification around the intended uses of `authenticateUser` vs `initiateAuth`? It's a bit unclear when to use `initiateAuth` when `authenticateUser` handles all manner of callbacks for an advanced Cognito auth flow. In our case, we are using typescript and leverage SMS, TOTP, and custom challenges, so we need to be able to easily handle those through the callbacks with the supplied typings.

With `initiateAuth` (as currently written), there doesn't appear to be an easy way to handle SRP in a custom auth flow unless we are expected to handle the SRP flow ourselves when using custom auth? If so, then we'll need typings to help us support that, but I'm really confused on why `authenticateUserDefaultAuth` handles SRP with custom auth and all callbacks. The only missing part is actually being able to call into that from `authenticateUser` -- which doesn't allow CUSTOM_AUTH, but in authenticateUserDefaultAuth it does support CUSTOM_AUTH. This PR just allowed the call to be made, so I'd love to understand the reasoning behind not allowing the call to be made when it does in fact support CUSTOM_AUTH. See the link below.

CUSTOM_AUTH supported in authenticateUserDefaultAuth:

https://github.com/aws/aws-amplify/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L245-L247

As a last resort, we can extend the typings to expose the private labeled `authenticateUserDefaultAuth` method, but I don't think that's the right solution. Thoughts?

**Comment by abemusic** [comment]
CC: @mlabieniec

**Comment by jasonamyers** [comment]
@buggy @yuntuowang @abemusic This is also a stumbling block for me, as this is how we handled it in the prior version of this library that's now retired. I've got an eye on upgrading to this lib, and it's not clear how to migrate with the prior behavior. Are we now expected to manage SRP etc ourselves that was in the authenticateUserDefaultAuth method and use initiateAuth? If so will you accept typings to make that possible? I wonder if there are others in this same boat?

**Comment by buggy** [comment]
Good point @abemusic.

@mlabieniec @yuntuowang I now agree with @abemusic that it should be included. Can one of you re-open this PR?

This PR covers CUSTOM_AUTH **with** a password.
#566 covers CUSTOM_AUTH **without** a password.

**Comment by abemusic** [comment]
@buggy thanks :) 

Off topic, but I'm curious what use cases you have for using passwordless auth? Is that a username followed by some MFA?

**Comment by buggy** [comment]
@abemusic I have two specific use cases:

1. An anonymous user account where the username is enough.

2. OAuth using a provider that Cognito doesn't support. I generate a one time password that can be used to log into Cognito User Pools.

**Comment by jason-h-michael** [comment]
We are facing the same problem.  We wrote our own MFA challenge, and need to do SRP before our custom MFA steps. `amplifyService.auth().signin(username, password)` doesn't work after setting flow type to CUSTOM because of the issue that this PR is attempting to fix.
Proactively, we made this simple one line change (from this PR) to our node_modules version of aws-amplify.  It worked perfectly from that point forward.  We will have to fork if this PR can't make it into the mainline - would really rather not do that.  :/

@mlabieniec @yuntuowang bump

**Comment by abemusic** [comment]
@jason-h-michael unfortunately, this PR was closed without any comment as to why. We decided shortly after the PR closed to fork and move forward. The last time I checked the SDK still did not support custom auth flows. Would love explanation or a comment from the devs on this.

**Comment by agkrall** [comment]
I have run into this as well... I need custom auth and this change makes it work the way our team would like it to.

**Comment by annjawn** [comment]
We also have the exact use case as @jason-h-michael . We have a custom MFA Challenge but it requires us to handle the SRP stuff ourselves which I am not sure why.

**Comment by annjawn** [comment]
I notice that the change in this PR has made it to the current version (perhaps through a different PR)

`} else if (this.authenticationFlowType === 'USER_SRP_AUTH' || this.authenticationFlowType === 'CUSTOM_AUTH') {`

However, it still kind of doesn't work. When I pass in password as `Auth.signIn(username, password)`, I now get an error even thought the Define Auth and Create Auth Lambdas get fired correctly. 

`TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.`

**Pull request closed without merging**
