### PR TITLE
add docs for protected storage level

### PR DESCRIPTION
**Pull request by ceich**
I noticed that the code in Storage.ts supports protected content, while the docs do not. I added minimal content to docs files, and updated the api comments in Storage.ts.

Note: I had to use `git commit -n` because the tests look to have been broken by previous commits.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ceich** [comment]
After some experimentation and code-reading, I'm having trouble figuring out how one user might easily access another's protected storage items, since the Storage class hardcodes the _current user's_ identity pool id in the _prefix() function.

It may not be worth adding protected to the docs unless there is a workaround.

My workaround would be to use the public level, and add my own prefixes (e.g. Cognito user pool `sub` values), to share files between users.

**Comment by mlabieniec** [comment]
@powerful23 does your pr for configurable prefixes address this?

**Comment by powerful23** [comment]
We need provide an option for people to pass ```idenetityId``` so that we can construct a path to get the object. For now users can only put or delete. The docs seems fine to me.

**Comment by mlabieniec** [comment]
@powerful23 does this pr address that?
https://github.com/aws/aws-amplify/pull/665

**Comment by powerful23** [comment]
@mlabieniec no that's about auth. What I mean is to do like
 ```
Storage.get(path, file, {
    level: 'protected', 
    identityId: 'XXXXXXX',
    ....
});
```
In that way one is able to read other's protected object

**Comment by ceich** [comment]
Thanks, waiting for `identityId` option so I can make use of `protected`!

**Pull request merged**
