### PR TITLE
add forceAliasCreation option to confirmSignUp

### PR DESCRIPTION
**Pull request by quangv**
#409, #449, #679 

*Description of changes:*
defaults to true, so to avoid breaking changes.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ossareh** [comment]
Hi there, I appreciate I'm not a maintainer of this project - so feel free to absolutely dismiss my feedback on this topic :) 

I opened #449 after doing much research into what was going on. So I'm glad it's being worked on, however I believe your implementation is not good software engineering. I'm a strong believer in not having boolean arguments passed to functions[1]; they're generally pretty unclear - more so you're defaulting to something that is "incorrect" as per the documentation.

I think the correct path here can go one of two ways:
 - pass an options argument to the function as it's last argument. If this method signature grows then you won't have random booleans in the middle of the method signature.
 - deprecate this method, create a new one, and remove this in time.

Given the fact this is a used library I think the first option is probably best. Following the advice of my linked post I think the second option is best.

Thanks for reading, I hope I've not offended. 

Cheers,

mike
(ex-AMZN :))

[1]: https://martinfowler.com/bliki/FlagArgument.html

**Comment by powerful23** [comment]
Thanks for your contributing. I will send another pr to fix this issue.

**Comment by powerful23** [comment]
#1017

**Comment by ossareh** [comment]
Hey there Zhuo, I've checked out #1017 and it looks good to me. My only
thought is that you should type the options being passed in, instead of
using `any`. It would look something like:

```lang=typescript
interface IConfirmSignupOpts {
    forceAliasCreation?: boolean;
}
```

This will help a range of issues from typos and through to providing a
strong promise to developers as to which API properties are supported by
aws-amplify.

**Comment by ossareh** [comment]
Hey there Zhuo, I've checked out #1017 and it looks good to me. My only
thought is that you should type the options being passed in, instead of
using `any`. It would look something like:

```lang=typescript
interface IConfirmSignupOpts {
    forceAliasCreation?: boolean;
}
```

This will help a range of issues from typos and through to providing a
strong promise to developers as to which API properties are supported by
aws-amplify.

**Comment by powerful23** [comment]
@ossareh Good point!

**Comment by quangv** [comment]
@powerful23 Great! Feel free to close this PR based on #1017

**Pull request closed without merging**
